{\rtf1\ansi\ansicpg949\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: JW Data Auto Scraper\
\
on:\
  schedule:\
    # \uc0\u47588 \u51068  \u54620 \u44397  \u49884 \u44036  \u49352 \u48317  4\u49884  (UTC 19:00)\
    - cron: '0 19 * * *'\
  workflow_dispatch:\
\
permissions:\
  contents: write\
\
jobs:\
  scrape-and-update:\
    runs-on: ubuntu-latest\
    \
    steps:\
    - name: Checkout repository\
      uses: actions/checkout@v4\
\
    - name: Set up Python\
      uses: actions/setup-python@v4\
      with:\
        python-version: '3.9'\
\
    - name: Install dependencies\
      run: pip install requests\
\
    # 1. \uc0\u50517 \u52629 \u46108  \u44592 \u50613 (data.zip)\u51060  \u51080 \u51004 \u47732  \u54396 \u45796 \
    - name: Unzip existing data\
      run: |\
        if [ -f data.zip ]; then\
          unzip -o data.zip\
          echo "\uc0\u9989  Unzipped data.zip"\
        fi\
\
    # 2. \uc0\u53356 \u47204 \u47084  \u49892 \u54665  (\u49352  \u45936 \u51060 \u53552  \u49688 \u51665  + \u54028 \u51068  \u51900 \u44060 \u44592  \u49688 \u54665 )\
    - name: Run Collector Script\
      run: python collector.py\
\
    # 3. \uc0\u51089 \u50629 \u51060  \u45149 \u45212  \u45824 \u50857 \u47049  \u50896 \u48376 \u51008  \u45796 \u49884  \u50517 \u52629  (GitHub \u50857 \u47049  \u51208 \u50557 )\
    - name: Zip master file\
      run: |\
        if [ -f jw_multilingual_data.json ]; then\
          zip -j data.zip jw_multilingual_data.json\
          echo "\uc0\u9989  Zipped master file to data.zip"\
        fi\
\
    # 4. \uc0\u44208 \u44284 \u47932 (\u48516 \u54624  \u54028 \u51068 \u46308  + \u50517 \u52629 \u54028 \u51068 )\u51012  \u44611 \u54728 \u48652 \u50640  \u50629 \u47196 \u46300 \
    - name: Commit and Push changes\
      run: |\
        git config --global user.name 'JW-Bot'\
        git config --global user.email 'actions@github.com'\
        \
        # \uc0\u51473 \u50836 : \u48516 \u54624 \u46108  json \u54028 \u51068 \u46308 \u51012  \u47784 \u46160  \u52628 \u44032 \
        git add jw_multilingual_data_*.json\
        git add jw_data_index.json\
        git add data.zip\
        \
        # \uc0\u48320 \u44221 \u49324 \u54637 \u51060  \u51080 \u51012  \u46412 \u47564  \u52964 \u48139 \
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update data [$(date +'%Y-%m-%d')]" && git push)}